---
title: "The Relationship Between Bike and Automobile Thefts in Toronto (2014-2023)"
author: "Maroosh Gillani"
thanks: "Code and data are available at: https://github.com/Maroosh-Gillani/toronto-bike-and-auto-thefts "
date: "21 January 2024"
date-format: long
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence." ########### UPDATE THIS ############
format: pdf
number-sections: true
execute: 
  echo: false
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(dplyr)
library(here)
library(ggplot2)

# Acquiring the cleaned theft data from cleaned_data.csv
theft_data <-
  read.csv(
    file=here("outputs/data/cleaned_data.csv")
  )

# Getting the total number of bikes theft each year and renaming columns to just years
total_bike_thefts <- 
  theft_data %>%
  select(starts_with("BIKETHEFT")) %>%
  slice(n()) %>%
  rename_with(~sub("BIKETHEFT_", "", .), starts_with("BIKETHEFT_"))

# Getting the total number of automobiles theft each year and renaming the columns to just years
total_auto_thefts <- 
  theft_data %>%
  select(starts_with("AUTOTHEFT")) %>%
  slice(n()) %>%
  rename_with(~sub("AUTOTHEFT_", "", .), starts_with("AUTOTHEFT_"))
```


# Introduction



# Data and Dataset



# Variables of Interest



# Data Visualization

```{r graph1, fig.cap="Number of Bike Thefts in Toronto from 2014 - 2023", echo=FALSE}
#| label: figure-1

# total bikes theft graphed
total_bike_thefts %>%
  gather(key = "Year", value = "BikeThefts", colnames(total_bike_thefts)) %>%
  ggplot(aes(x = Year, y = BikeThefts)) +
  geom_col() +
  theme_minimal() +
  labs(x = "Year", y = "Number of Bike Thefts")
```
Some analysis about bike thefts...

```{r graph2, fig.cap="Number of Automobile Thefts in Toronto from 2014 - 2023", echo=FALSE}
#| label: figure-2

# total automobiles theft graphed
total_auto_thefts %>%
  gather(key = "Year", value = "AutoThefts", colnames(total_auto_thefts)) %>%
  ggplot(aes(x = Year, y = AutoThefts)) +
  geom_col() +
  theme_minimal() +
  labs(x = "Year", y = "Number of Automobile Thefts")
```
Some analysis about automobile thefts

```{r graph3, fig.cap="Side by Side Comparison of The Number of Bike and Automobile Thefts", echo=FALSE}
#| label: figure-3

# Combine both data frames
combined_data <- bind_rows(
  mutate(total_bike_thefts, Type = "Bike"),
  mutate(total_auto_thefts, Type = "Auto")
)

# Create a side-by-side bar plot
combined_data %>%
  gather(key = "Year", value = "Thefts", -Type) %>%
  ggplot(aes(x = Year, y = Thefts, fill = Type)) +
  geom_col(position = position_dodge(width = 0.8), width = 0.7) +
  theme_minimal() +
  labs(x = "Year", y = "Number of Thefts") +
  scale_fill_manual(values = c("Bike" = "navy", "Auto" = "dark red"))  # Customize fill colors
```
Some analysis about the bike thefts in contrast to auto thefts

# Conclusion



# References


